axoniq:
  axonserver:
    name: eventstore-transformations-local
    hostname: localhost
    #standalone: true
    autocluster:
      first:
      contexts: default
    accesscontrol:
      enabled: false
    devmode:
      enabled: true
